# Generated by Django 4.0.6 on 2022-08-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField()),
                ('maxprofit', models.FloatField(max_length=100)),
                ('maxloss', models.FloatField(max_length=100)),
                ('rrr', models.FloatField(max_length=10)),
                ('breakeven1', models.FloatField(max_length=100)),
                ('breakeven2', models.FloatField(max_length=100)),
                ('projectedreturns', models.FloatField(max_length=10)),
                ('marginavailable', models.FloatField(max_length=100)),
                ('marginneeded', models.FloatField(max_length=100)),
                ('marginused', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='displaydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.FloatField(max_length=10)),
                ('percentagechange', models.FloatField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='niftyindex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('into', models.FloatField(max_length=10)),
                ('inth', models.FloatField(max_length=10)),
                ('intl', models.FloatField(max_length=10)),
                ('intc', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='optionchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry', models.CharField(max_length=10)),
                ('strike', models.FloatField(max_length=10)),
                ('cltp', models.FloatField(max_length=100)),
                ('coi', models.FloatField(max_length=100)),
                ('pltp', models.FloatField(max_length=100)),
                ('poi', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField()),
                ('bs', models.CharField(max_length=1)),
                ('expiry', models.CharField(max_length=10)),
                ('strike', models.FloatField(max_length=10)),
                ('cepe', models.CharField(max_length=2)),
                ('lots', models.IntegerField()),
                ('entry', models.FloatField(max_length=10)),
                ('stoploss', models.FloatField(max_length=10)),
                ('price', models.FloatField(max_length=10)),
                ('pnl', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='premium',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ltp', models.FloatField(max_length=10)),
            ],
        ),
    ]
