# Generated by Django 4.0.6 on 2022-08-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradesim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField()),
                ('bs', models.CharField(max_length=1)),
                ('expiry', models.CharField(max_length=10)),
                ('strike', models.FloatField(max_length=10)),
                ('cepe', models.CharField(max_length=2)),
                ('lots', models.IntegerField()),
                ('entry', models.FloatField(max_length=10)),
                ('stoploss', models.FloatField(max_length=10)),
            ],
        ),
    ]
