# Generated by Django 4.0.6 on 2022-08-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradesim', '0002_builder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='builder',
            old_name='entry',
            new_name='price',
        ),
    ]
