# Generated by Django 4.0.6 on 2022-08-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradesim', '0003_rename_entry_builder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='builder',
            name='token',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optionchain',
            name='token',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positions',
            name='token',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
