# Generated by Django 4.0.6 on 2022-08-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradesim', '0004_builder_token_optionchain_token_positions_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='inview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField()),
                ('expiry', models.CharField(max_length=10)),
            ],
        ),
    ]
