# Generated by Django 4.0.6 on 2022-08-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradesim', '0005_inview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionchain',
            old_name='token',
            new_name='ctoken',
        ),
        migrations.AddField(
            model_name='optionchain',
            name='ptoken',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
