# Generated by Django 4.0.6 on 2022-08-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradesim', '0006_rename_token_optionchain_ctoken_optionchain_ptoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builder',
            name='cepe',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='createdon',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='expiry',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='lots',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='price',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='stoploss',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='strategy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='strike',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
