# Generated by Django 4.0.6 on 2022-08-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradesim', '0007_alter_builder_cepe_alter_builder_createdon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='pnl',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='positions',
            name='price',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='positions',
            name='stoploss',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
