# Generated by Django 4.0.6 on 2022-08-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradesim', '0009_remove_builder_stoploss_positions_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='niftyindex',
        ),
        migrations.DeleteModel(
            name='premium',
        ),
    ]
