# Generated by Django 4.0.6 on 2022-08-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradesim', '0010_delete_niftyindex_delete_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
